### ISSUE TITLE
Addon: Transmission wont install

### ISSUE THREAD

**Issue by JohnRebol** [pierrickrouxel/hassio-addon-transmission#5]
In the add-on store, when i hit install button, nothing happens. please help. repository is added with no issue. I installed Hassio 2 hours ago.

**Comment by karampok** [comment]
I tried it also and I have some behavior, here are the logs
```
Can't build 8cc98bc5/armv7-addon-transmission:dev: The command 
'/bin/ash -o pipefail -c apk add --no-cache nginx=1.14.2-r0' returned a non-zero code: 1
```

thx

**Comment by robertostlund** [comment]
I'm getting the same error when trying to install transmission addon with hass.io

**Comment by bakasdim** [comment]
same here. not installable on hassio running on a raspberry pi 3b+.

**Comment by CanuckianOz** [comment]
Me neither. Getting the same error as @karampok .

**Comment by CanuckianOz** [comment]
@pierrickrouxel is this going to be addressed or has the project been abandoned?

**Comment by pierrickrouxel** [comment]
I dont use this project anymore so I will not fix issues. But if you want to fix it and create a pull request I will merge it quickly.

**Comment by CanuckianOz** [comment]
This was a PITA to fix as I'm only an elec eng and not developer and went down a few dead ends. But the fix was removing the specific nginx version reference in Dockerfile, and adding armv7 architecture support, otherwise I couldn't get it to install and then it wouldn't start and no logs gave any hints. 

I'll run some tests to see if I can get it to work fully.  I've never done a pull request before so bear with me while I stuff around with it.

**Comment by paolorovella** [comment]
It seems i've fixed it 🙂 https://github.com/pierrickrouxel/hassio-addon-transmission/pull/9
